# Generated by Django 5.1 on 2025-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Уникальный ключ для текста, например 'home.title'", max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('text_ky', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='PageTextGlobalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
