# Generated by Django 5.1 on 2025-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('osago', 'ОСАГО'), ('nc', 'НС'), ('vzr', 'ВЗР'), ('faq', 'FAQ')], max_length=10)),
                ('question', models.CharField(max_length=255)),
                ('question_ru', models.CharField(max_length=255, null=True)),
                ('question_ky', models.CharField(max_length=255, null=True)),
                ('answer', models.TextField()),
                ('answer_ru', models.TextField(null=True)),
                ('answer_ky', models.TextField(null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
