# Generated by Django 5.1 on 2025-06-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_qaentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qaentry',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы и ответы'},
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='answer',
            field=models.TextField(help_text='Текст ответа', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='answer_ky',
            field=models.TextField(help_text='Текст ответа', null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='answer_ru',
            field=models.TextField(help_text='Текст ответа', null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения', verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='question',
            field=models.CharField(help_text='Текст вопроса', max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='question_ky',
            field=models.CharField(help_text='Текст вопроса', max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='question_ru',
            field=models.CharField(help_text='Текст вопроса', max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='qaentry',
            name='type',
            field=models.CharField(choices=[('osago', 'ОСАГО'), ('nc', 'НС'), ('vzr', 'ВЗР'), ('faq', 'FAQ')], db_index=True, help_text='Категория вопроса: ОСАГО, НС, ВЗР, FAQ', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterUniqueTogether(
            name='qaentry',
            unique_together={('type', 'order')},
        ),
        migrations.AddIndex(
            model_name='qaentry',
            index=models.Index(fields=['type', 'order'], name='common_qaen_type_d7c67b_idx'),
        ),
    ]
