# Generated by Django 5.1 on 2025-08-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_qaentry_options_alter_qaentry_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetext',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='page_files/', verbose_name='Файл'),
        ),
    ]
