# Generated by Django 5.1 on 2026-01-13 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_chargepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_id', models.CharField(max_length=128, verbose_name='ID платежа у банка')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на оплату')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('success', 'Оплачено'), ('pending', 'В ожидании'), ('failed', 'Не удалось')], default='pending', max_length=20, verbose_name='Статус')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('webhook_payload', models.JSONField(blank=True, null=True, verbose_name='Webhook-ответ')),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to='account.chargepoint', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'QR-платеж',
                'verbose_name_plural': 'QR-платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
