# Generated by Django 5.1 on 2025-12-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('cp_id', models.CharField(help_text='ID станции (cp_id в URL WebSocket)', max_length=64, primary_key=True, serialize=False, verbose_name='Charge Point ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Charge Point',
                'verbose_name_plural': 'Charge Points',
            },
        ),
    ]
