# Generated by Django 5.1 on 2025-12-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_chargepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='active_transaction_id',
            field=models.IntegerField(blank=True, help_text='Последний активный OCPP transactionId', null=True, verbose_name='Active transaction ID'),
        ),
    ]
