# Generated by Django 5.1 on 2026-01-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_chargepoint_active_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='charge24_cp_id',
            field=models.CharField(blank=True, help_text='ID станции в системе Charge24', max_length=64, null=True, verbose_name='Charge24 CP ID'),
        ),
    ]
