# Generated by Django 5.1 on 2026-01-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_chargepoint_charge24_cp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='payment_qr_link',
            field=models.URLField(blank=True, max_length=2000, null=True, verbose_name='QR ссылка для оплаты'),
        ),
    ]
