# Generated by Django 5.1 on 2026-01-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_chargepoint_payment_qr_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargePoint',
        ),
    ]
