# Generated by Django 5.1 on 2026-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_chargepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cp_id', models.CharField(help_text='ID станции (cp_id в URL WebSocket)', max_length=64, unique=True, verbose_name='Charge Point ID')),
                ('charge24_cp_id', models.CharField(blank=True, help_text='ID станции в системе Charge24', max_length=64, null=True, verbose_name='Charge24 CP ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('active_transaction_id', models.IntegerField(blank=True, help_text='Последний активный OCPP transactionId', null=True, verbose_name='Active transaction ID')),
                ('payment_qr_link', models.URLField(blank=True, max_length=2000, null=True, verbose_name='QR ссылка для оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Charge Point',
                'verbose_name_plural': 'Charge Points',
            },
        ),
    ]
