# Generated by Django 5.1 on 2026-01-18 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_chargepoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSMSService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('charge24', 'Charge24'), ('other_csms', 'Other CSMS')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('ws_url_template', models.CharField(help_text='Template: wss://charge24.app/c/{cp_id}', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chargepoint',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chargepoint',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(blank=True, null=True)),
                ('connector_id', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('preparing', 'Preparing'), ('charging', 'Charging'), ('stopped', 'Stopped'), ('completed', 'Completed'), ('error', 'Error')], default='preparing', max_length=20)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumed_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cost_per_kwh', models.DecimalField(decimal_places=2, default=12.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('last_meter_value', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chargepoint')),
            ],
        ),
        migrations.CreateModel(
            name='ChargePointCSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_cp_id', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('charge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.chargepoint')),
                ('csms_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.csmsservice')),
            ],
            options={
                'unique_together': {('charge_point', 'csms_service')},
            },
        ),
    ]
