# Generated by Django 5.1 on 2026-01-18 03:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_csmsservice_chargepoint_is_occupied_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csmsservice',
            options={'ordering': ('name',), 'verbose_name': 'CSMS сервис', 'verbose_name_plural': 'CSMS сервисы'},
        ),
        migrations.AddField(
            model_name='csmsservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='csmsservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='csmsservice',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='csmsservice',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название сервиса'),
        ),
        migrations.AlterField(
            model_name='csmsservice',
            name='service_type',
            field=models.CharField(choices=[('charge24', 'Charge24'), ('other_csms', 'Other CSMS')], db_index=True, max_length=50, verbose_name='Тип сервиса'),
        ),
        migrations.AlterField(
            model_name='csmsservice',
            name='ws_url_template',
            field=models.CharField(help_text='Пример: wss://charge24.app/c/{cp_id}', max_length=255, validators=[django.core.validators.RegexValidator(message='URL должен быть wss:// и содержать {cp_id}', regex='^wss:\\/\\/.+\\{cp_id\\}.+')], verbose_name='WebSocket URL шаблон'),
        ),
    ]
