# Generated by Django 5.1 on 2026-01-18 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_csmsservice_options_csmsservice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargepointcsms',
            options={'ordering': ('charge_point',), 'verbose_name': 'Связь станции с CSMS', 'verbose_name_plural': 'Связи станций с CSMS'},
        ),
        migrations.AlterModelOptions(
            name='chargingsession',
            options={'verbose_name': 'Базовая модель', 'verbose_name_plural': 'Базовые модели'},
        ),
        migrations.RemoveField(
            model_name='chargepointcsms',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='chargepointcsms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargepointcsms',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='chargepointcsms',
            name='charge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csms_links', to='account.chargepoint', verbose_name='Зарядная станция'),
        ),
        migrations.AlterField(
            model_name='chargepointcsms',
            name='csms_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_points', to='account.csmsservice', verbose_name='CSMS сервис'),
        ),
        migrations.AlterField(
            model_name='chargepointcsms',
            name='remote_cp_id',
            field=models.CharField(help_text='Идентификатор станции во внешнем CSMS', max_length=100, verbose_name='ID станции в CSMS'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
    ]
