# Generated by Django 5.1 on 2026-01-18 04:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_chargepointcsms_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chargingsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия зарядки', 'verbose_name_plural': 'Сессии зарядки'},
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='id_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='start_meter_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Показание счетчика при старте (Wh)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='charge_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='account.chargepoint'),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='consumed_kwh',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Потреблено кВт⋅ч', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='cost_per_kwh',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Стоимость за 1 кВт⋅ч', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Начальный баланс в сомах', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='last_meter_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Последнее показание счетчика (Wh)', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='status',
            field=models.CharField(choices=[('preparing', 'Подготовка'), ('charging', 'Зарядка'), ('stopped', 'Остановлена'), ('completed', 'Завершена'), ('error', 'Ошибка')], db_index=True, default='preparing', max_length=20),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Общая стоимость', max_digits=10),
        ),
        migrations.AlterField(
            model_name='chargingsession',
            name='transaction_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['charge_point', 'status'], name='charging_se_charge__57d218_idx'),
        ),
        migrations.AddIndex(
            model_name='chargingsession',
            index=models.Index(fields=['transaction_id'], name='charging_se_transac_6eaf70_idx'),
        ),
        migrations.AlterModelTable(
            name='chargingsession',
            table='charging_sessions',
        ),
    ]
