# Generated by Django 5.1 on 2026-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_chargingsession_options_chargingsession_id_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargepoint',
            name='occupied_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='csmsservice',
            name='ws_url_template',
            field=models.CharField(help_text='Пример: wss://charge24.app/c/{cp_id}', max_length=255, verbose_name='WebSocket URL шаблон'),
        ),
    ]
