# Generated by Django 5.1 on 2026-03-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_migrate_charge24_to_csms_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="CSMSTransactionMapping",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата последнего обновления")),
                ("csms_name", models.CharField(db_index=True, max_length=100)),
                ("csms_transaction_id", models.IntegerField(db_index=True)),
                ("station_transaction_id", models.IntegerField(db_index=True)),
                ("id_tag", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("charge_point", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="tx_mappings", to="account.chargepoint")),
            ],
            options={
                "verbose_name": "CSMS transaction mapping",
                "verbose_name_plural": "CSMS transaction mappings",
                "indexes": [
                    models.Index(fields=["charge_point", "csms_name", "csms_transaction_id"], name="account_csms_charge__2e8861_idx"),
                    models.Index(fields=["charge_point", "station_transaction_id"], name="account_csms_charge__2d8f3a_idx"),
                    models.Index(fields=["charge_point", "is_active"], name="account_csms_charge__f8d31d_idx"),
                ],
            },
        ),
    ]
